// <auto-generated />
namespace Mentoring9_Orm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Version_10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version_10));
        
        string IMigrationMetadata.Id
        {
            get { return "201803231029452_Version_1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
